"""Default constants for the integration."""

DEFAULT_LISTEN_PORT = 5020
DEFAULT_DONGLE_PORT = 502
DEFAULT_CACHE_TTL = 5.0
DEFAULT_MIN_UPSTREAM_INTERVAL = 1.0
DEFAULT_CONNECT_TIMEOUT = 10.0
DEFAULT_RECONNECT_DELAY = 5.0
